### ISSUE TITLE
New Apple LLVM Clang not supported

### ISSUE THREAD

**Issue by andraspalfi** [ioquatix/ffi-clang#37]
The new clang shipped with XCode 7 doesn't provide the original clang version info so the parsein utils.rb fails to get the version and stops.
Parsing the Apple version is possible but results in a different version of course - however the code seems to work fine.
>> if parts = clang_version_string.match(/(?:clang version|based on LLVM|Apple LLVM version) (\d+)\.(\d+)(svn)?/) <<
Do you plan to support the new Apple LLVM version?

**Comment by dholzenburg** [comment]
Any updates on this one?

**Comment by ioquatix** [comment]
Can you please submit a PR and I will merge and release.

**Comment by ioquatix** [comment]
Okay I've merged a PR to add support for this, and released 0.3.0 but the specs are still failing because the string doesn't match the spec expectation.. I guess that is an easy fix.

Do you think there is any way to get the version numbers rather than having to parse the string?

**Comment by dholzenburg** [comment]
After some researching I found this:

[(http://lists.llvm.org/pipermail/llvm-dev/2015-September/090560.html)]

At the moment I don't have any idea how to deal with that.

**Comment by ioquatix** [comment]
I was actually thinking perhaps we should just remove the version check. It was more important when 3.2 and 3.3. and 3.4 all had different functionality which we had to be careful about. What do you think?

**Comment by dholzenburg** [comment]
Maybe yes. It's probably better to check the availability of features instead the version string. 

But I have to admit my knowledge about the whole topic is ending at this point. I am no clang expert and I don't have any real idea about ruby and ffi.

**Comment by ioquatix** [comment]
I think using the version to check for features is a bad idea ultimately. Especially we have a case where it doesn't work. I think I'll rip out all the version detection code and related decisions. we won't support any old versions of libclang (< 3.5). Who cares about those versions now anyway? It would be nice to do a 1.0 release too, with solid support for a specific minimum version.
