### ISSUE TITLE
Releases to rubygems.org?

### ISSUE THREAD

**Issue by k0kubun** [ioquatix/ffi-clang#56]
I noticed that the last release was 3 years ago while there are some improvements in the master branch. Do you install ffi-clang from GitHub and not use rubygems.org?

**Comment by ioquatix** [comment]
It's been a long time since I maintained this gem. I am happy to make a new release, I would need to spend some time reviewing the code. Last time I used it, clang 3.x was still popular.

**Comment by k0kubun** [comment]
Thanks! I've been using it with libclang-14 with no problems so far, except for the fact that the soname is changed and I need to specify `$LIBCLANG` manually.

**Comment by k0kubun** [comment]
@ioquatix Can we publish it as a beta or something? ruby/ruby has been using the master branch for a while with `make mjit-bindgen` that runs on every revision without any problem. It started to feel annoying that it needs to fetch the library from GitHub.

**Comment by ioquatix** [comment]
Sure, I will try to do it now... but if it requires more work, it might be tomorrow.

**Comment by ioquatix** [comment]
I've released the exact `main` branch using the existing gemspec as `v0.7.0` but... we need a lot of work... this gem is still using travis. I think I'll follow up with v0.8.0 soon but I'll probably drop support for old clang/LLVM... because I think it's going to be really hard to test.

**Comment by k0kubun** [comment]
Thank you so much!

**Comment by ioquatix** [comment]
I started working on updated GitHub actions tests here: https://github.com/ioquatix/ffi-clang/pull/58
