### ISSUE TITLE
C++ AST Introspection

### ISSUE THREAD

**Issue by cfis** [ioquatix/ffi-clang#65]
I would like to add support for C++ AST introspection. See https://clang.llvm.org/doxygen/group__CINDEX__CPP.html#ga0c6580828662fd27cb7152e47c1b3e4e.

Would you prefer these to be added to `clang/lib/cursor.rb` or put in a separate file such as `clang/lib/cxx_introspection.rb`? Then I assume add methods to `clang/cursor.rb`?

**Comment by ioquatix** [comment]
I think it's okay to add it to cursor but it's also okay to add it to a separate file if there are a lot of methods and you think it's better organisation.
