### ISSUE TITLE
Why does Lib.bitmask_from take a Hash?

### ISSUE THREAD

**Issue by cfis** [ioquatix/ffi-clang#68]
`Lib.bimask_from` takes a hash (the `opts` parameter) but does not use the hash value:

https://github.com/ioquatix/ffi-clang/blob/main/lib/ffi/clang/lib.rb#L69

The test show the following cases work:

```
index.parse_translation_unit(fixture_path("a.c"), [], [], [:incomplete, :single_file_parse, :cache_completion_results])
index.parse_translation_unit(fixture_path("a.c"), [], [], {:incomplete => 654, :single_file_parse => 8, :cache_completion_results => 93})
```

However, `Lib.bimask_from` only accepts values that are defined in the enum passed to it (in this case `Lib::TranslationUnitFlags`). Thus the hash seems pointless - and at least to me very non-intuitive.

But maybe this can't change for backwards compatibility reasons?

**Comment by ioquatix** [comment]
In this case, I don't think backwards compatibility is a huge concern, so I'd suggest fixing the method to make more sense.
