### ISSUE TITLE
How to build gem?

### ISSUE THREAD

**Issue by cfis** [ioquatix/ffi-clang#77]
Sorry for the dumb question, but how does one build the ffi-clang gem? There isn't a rakefile that I see. I do see references to a gem called teapot, but its rubygem page doesn't link to any helpful documentation.

I would like to be able to build the gem locally with changes I have made, and then deploy it locally.

**Comment by ioquatix** [comment]
If you mean the gem release process, it's documented here:

https://github.com/ioquatix/bake-gem?tab=readme-ov-file#usage

**Comment by ioquatix** [comment]
(if you try to build a signed package, it probably won't work as you don't have the private key for doing a release).

**Comment by cfis** [comment]
I see - thanks!
